# Generated by Django 5.2 on 2025-10-16 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BooksCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True, verbose_name='Url')),
                ('books_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Категорию',
                'verbose_name_plural': 'Категории',
                'db_table': 'book_category',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='BooksRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Название Книги')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True, verbose_name='Url')),
                ('author_name', models.CharField(max_length=150, verbose_name='Автор книги')),
                ('reliz_year', models.CharField(max_length=150, verbose_name='Год выпуска')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='book_images', verbose_name='Изображение')),
                ('likes', models.IntegerField(blank=True, null=True, verbose_name='Лайки')),
                ('file', models.FileField(blank=True, null=True, upload_to='book_file', verbose_name='Файл книги в pdf')),
                ('upload_message', models.TextField(blank=True, null=True)),
                ('upload_status', models.CharField(choices=[('pending', 'В ожидании'), ('success', 'успешно'), ('error', 'ошибка')], default='pending', max_length=20)),
                ('book_lists', models.IntegerField(blank=True, null=True, verbose_name='Количество листов')),
                ('book_id', models.CharField(blank=True, max_length=150, null=True, verbose_name='id книги в монго')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.bookscategories', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Книги',
                'verbose_name_plural': 'Книги',
                'db_table': 'book',
                'ordering': ['id'],
            },
        ),
    ]
