# Generated by Django 5.2 on 2025-10-24 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booksread',
            name='ratings',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='booksread',
            name='upload_status',
            field=models.CharField(choices=[('pending', 'В ожидании'), ('success', 'успешно'), ('error', 'ошибка'), ('delete', 'книга удалена')], default='pending', max_length=20),
        ),
    ]
