# Generated by Django 5.2 on 2025-10-24 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_booksread_ratings_alter_booksread_upload_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booksread',
            name='reliz_year',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Год выпуска'),
        ),
    ]
